//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCMSCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public int Idx { get; set; }
        public byte MeasureType { get; set; }
        public int ChannelId { get; set; }
        public Nullable<int> LowFreq { get; set; }
        public Nullable<int> HighFreq { get; set; }
        public Nullable<int> Interval1 { get; set; }
        public Nullable<int> Interval2 { get; set; }
        public Nullable<int> Interval3 { get; set; }
    }
}
