//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCMSCommon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestCmsEntities : DbContext
    {
        public TestCmsEntities()
            : base("name=TestCmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Measurement> Measurement { get; set; }
        public DbSet<Receiver> Receiver { get; set; }
        public DbSet<TrendData> TrendData { get; set; }
        public DbSet<Entity1> Entity1Set { get; set; }
    }
}
