//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCMSCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receiver
    {
        public int Idx { get; set; }
        public byte ReceiverType { get; set; }
        public string Ip { get; set; }
        public string FilePath { get; set; }
        public int Port { get; set; }
        public byte SerializerType { get; set; }
    }
}
