//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCMSCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrendData
    {
        public int Idx { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public int MeasureId { get; set; }
        public double Scalar { get; set; }
    }
}
